require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.0
  DisplayCopNames: true

LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

RSpec/NestedGroups:
  Max: 4
